version: "3.8"
services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: maeasoftworks
      MINIO_ROOT_PASSWORD: normativecontrol
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
  postgres:
    image: postgres
    restart: no
    environment:
      POSTGRES_PASSWORD: maeasoftworks
      POSTGRES_DB: normative-control
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
volumes:
  minio-storage:
  postgres-data: