package com.maeasoftworks.normativecontrol.dtos.enums

enum class ErrorType {
    // page size
    PAGE_WIDTH_IS_INCORRECT,
    PAGE_HEIGHT_IS_INCORRECT,

    // page margins
    PAGE_MARGIN_TOP_IS_INCORRECT,
    PAGE_MARGIN_LEFT_IS_INCORRECT,
    PAGE_MARGIN_BOTTOM_IS_INCORRECT,
    PAGE_MARGIN_RIGHT_IS_INCORRECT,

    // chapters
    CHAPTER_INCORRECT,
    CHAPTER_COUNT_MISMATCH,
    CHAPTER_FRONT_PAGE_NOT_FOUND,
    CHAPTER_ANNOTATION_NOT_FOUND,
    CHAPTER_CONTENTS_NOT_FOUNDS,
    CHAPTER_INTRODUCTION_NOT_FOUND,
    CHAPTER_BODY_NOT_FOUND,
    CHAPTER_CONCLUSION_NOT_FOUND,
    CHAPTER_REFERENCES_NOT_FOUND,
    CHAPTER_APPENDIX_NOT_FOUND,

    INCORRECT_TEXT_FONT,
    INCORRECT_TEXT_COLOR,
    INCORRECT_HEADER_ALIGNMENT,
    HEADER_IS_NOT_UPPERCASE,
    INCORRECT_FONT_SIZE,
    INCORRECT_REGULAR_TEXT_ALIGNMENT,
    ITALIC_TEXT,
    REGULAR_TEXT_WAS_BOLD,
    REGULAR_TEXT_WAS_UNDERLINED,
    STRIKETHROUGH,
    HIGHLIGHT,
    INCORRECT_TEXT_DIRECTION,
    BORDER,
    BACKGROUND_FILLED,

    // annotation
    ANNOTATION_MUST_NOT_CONTAINS_MEDIA,

    // whitespace
    WHITESPACE_INCORRECT_TEXT_FONT,
    WHITESPACE_INCORRECT_TEXT_COLOR,
    WHITESPACE_INCORRECT_FONT_SIZE,
    WHITESPACE_INCORRECT_ALIGNMENT,
    WHITESPACE_ITALIC,
    WHITESPACE_BOLD,
    WHITESPACE_UNDERLINED,
    WHITESPACE_STRIKETHROUGH,
    WHITESPACE_HIGHLIGHT,
    WHITESPACE_INCORRECT_TEXT_DIRECTION,
    WHITESPACE_BORDER,
    WHITESPACE_BACKGROUND_FILLED
}