server:
  port: ${PORT}

controllers:
  docs: true
  api: true

spring:
  datasource:
    password: ${database_password}
    username: ${database_user}
    url: ${database_url}

app:
  jwtSecret: ${jwt_secret}