document:
  page:
    margin:
      bottom: 1134
      left: 1701
      right: 850
      top: 1134
    width: 11906
    height: 16838
  sectors:
    keywords:
      annotation: РЕФЕРАТ,
      contents: СОДЕРЖАНИЕ,ОГЛАВЛЕНИЕ
      introduction: ВВЕДЕНИЕ,
      conclusion: ЗАКЛЮЧЕНИЕ,
      references: БИБЛИОГРАФИЧЕСКИЙ СПИСОК,СПИСОК ИСПОЛЬЗОВАННОЙ ЛИТЕРАТУРЫ,СПИСОК ЛИТЕРАТУРЫ,
      appendix: ПРИЛОЖЕНИЕ,ПРИЛОЖЕНИЯ,
spring:
  datasource:
    password: meaasoftworks52(
    username: meaasoftworks
    url: jdbc:h2:~/database/documents
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
server:
  port: '8080'
