controllers:
  docs: true
  api: true

spring:
  datasource:
    password: maeasoftworks52(
    username: maeasoftworks
    url: jdbc:hsqldb:~/database/NormativeControl
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8080
