controllers:
  docs: true
  api: true

spring:
  datasource:
    password: maeasoftworks
    username: maeasoftworks
    url: jdbc:postgresql://localhost:5432/documents
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

app:
  jwtSecret: K5b4qldMjy
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 2592000000