document:
  page:
    margin:
      bottom: '56'
      left: '85'
      right: '42'
      top: '56'
    width: '595'
    height: '841'
  sectors:
    keywords:
      annotation: РЕФЕРАТ,
      contents: СОДЕРЖАНИЕ,ОГЛАВЛЕНИЕ
      introduction: ВВЕДЕНИЕ,
      body: ГЛАВА,
      conclusion: ЗАКЛЮЧЕНИЕ,
      references: БИБЛИОГРАФИЧЕСКИЙ СПИСОК,СПИСОК ИСПОЛЬЗОВАННОЙ ЛИТЕРАТУРЫ,СПИСОК ЛИТЕРАТУРЫ,
      appendix: ПРИЛОЖЕНИЕ,ПРИЛОЖЕНИЯ,
spring:
  datasource:
    password: meaasoftworks52(
    username: meaasoftworks
    url: jdbc:h2:~/database/documents
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
server:
  port: '8080'
