document:
  keywords:
    annotation: РЕФЕРАТ,
    contents: СОДЕРЖАНИЕ,ОГЛАВЛЕНИЕ
    introduction: ВВЕДЕНИЕ,
    conclusion: ЗАКЛЮЧЕНИЕ,
    references: БИБЛИОГРАФИЧЕСКИЙ СПИСОК,СПИСОК ИСПОЛЬЗОВАННОЙ ЛИТЕРАТУРЫ,СПИСОК ЛИТЕРАТУРЫ,СПИСОК ИСТОЧНИКОВ
    appendix: ПРИЛОЖЕНИЕ,ПРИЛОЖЕНИЯ,

controllers:
  documentation: false

spring:
  datasource:
    password: maeasoftworks52(
    username: maeasoftworks
    url: jdbc:hsqldb:~/database/NormativeControl
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
      enabled: true

server:
  port: 8080
