package normativecontrol.implementation.urfu

import normativecontrol.core.mistakes.MistakeReason

internal enum class Reason(override val description: String, val expected: String? = null) : MistakeReason {
    ChapterOrderMismatch("Неверный порядок разделов. Методические указания, п. 3.1"),
    IncorrectLineSpacingHeader("Некорректный межстрочный интервал заголовка. Методические указания, п. 6.2"),
    IncorrectLineSpacingText("Некорректный межстрочный интервал текста. Методические указания, п. 6.1"),
    TabInList("Запрещено использование табуляции в качестве разделителя после маркера списка. Методические указания, п. 6.3"),
    ForbiddenMarkerTypeLevel1("Данный вид маркера списка запрещен. Используйте ненумерованный список либо русские строчные буквы. Методические указания, п. 6.3"),
    ForbiddenMarkerTypeReferences("Данный вид маркера списка запрещен. Используйте нумерованный список. Методические указания, п. 6.10"),
    ReferenceNotMentionedInText("Не найдено ссылок для этого источника. Если они есть, убедитесь, что ссылки соответствуют правилам оформления. Методические указания, п. 6.10"),
    LeftIndentOnHeader("Обнаружен отступ слева у заголовка раздела. Методические указания, п. 6.1"),
    LeftIndentOnText("Обнаружен отступ слева у текста. Методические указания, п. 6.1"),
    LeftIndentOnPictureDescription("Обнаружен отступ слева у подписи рисунка. Методические указания, п. 6.8"),
    RightIndentOnHeader("Обнаружен отступ справа у заголовка раздела. Методические указания, п. 6.2"),
    RightIndentOnText("Обнаружен отступ справа у текста. Методические указания, п. 6.1"),
    IncorrectFirstLineIndentInText("Неверный отступ первой строки у текста. Методические указания, п. 6.1"),
    IncorrectFirstLineIndentInHeader("Неверный отступ первой строки у заголовка. Методические указания, п. 6.2"),
    IncorrectFirstLineIndentInPictureDescription("Неверный отступ первой строки у подписи рисунка. Методические указания, п. 6.8"),
    IncorrectFirstLineIndentInTableTitle("Неверный отступ первой строки у заголовка таблицы. Методические указания, п. 6.7"),
    IncorrectLeftIndentInList("Неверный отступ слева в списке. Методические указания, п. 6.3"),
    IncorrectJustifyOnBodyHeader("Заголовок раздела основной части должен быть выровнен по ширине. Методические указания, п. 6.2"),
    IncorrectJustifyOnHeader("Заголовок раздела должен быть выровнен по центру. Методические указания, п. 6.2"),
    IncorrectJustifyOnPictureDescription("Подпись рисунка должна быть выровнена по центру. Методические указания, п. 6.8"),
    IncorrectJustifyOnTableTitle("Заголовок таблицы должен быть выровнен по левому краю. Методические указания, п. 6.7"),
    IncorrectJustifyOnText("Текст должен быть выровнен по ширине. Методические указания, п. 6.1"),
    BackgroundColor("Найден цветной фон"),
    SpacingBefore("Найден интервал перед абзацем. Методические указания, п. 6.1"),
    SpacingAfter("Найден интервал после абзаца. Методические указания, п. 6.1"),
    IncorrectFont("Неверный шрифт: необходим Times New Roman. Методические указания, п. 6.1"),
    IncorrectPictureDescriptionPattern("Неверный формат подписи рисунка. Методические указания, п. 6.8"),
    TableWithoutTitle("Не найден заголовок таблицы/продолжение таблицы. Методические указания, п. 6.7"),
    Italic("Найден курсивный текст"),
    BoldText("Найден жирный текст"),
    IncorrectFontSize("Неверный размер шрифта"),
    IncorrectTextColor("Неверный цвет текста", "черный или авто"),
    LeftIndentOnCode("Обнаружен отступ слева у блока кода"),
    RightIndentOnCode("Обнаружен отступ справа у блока кода"),
    FirstLineIndentOnCode("Обнаружен отступ первой строки у блока кода"),
    JustifyOnCode("Блок кода должен быть выровнен по левому краю"),
    IncorrectFontSizeInCode("Неверный размер шрифта в коде"),
    IncorrectLineSpacingInCode("Некорректный межстрочный интервал в коде"),
    CodeBlockWasTooBig("Слишком большой блок кода")
}