ktor:
  deployment:
    port: 80
  application:
    modules:
      - ru.maeasoftworks.normativecontrol.api.ApplicationKt.allModules

jwt:
  issuer: "???"
  audience: "???"
  realm: "???"
  secret: "???"
  jwtTokenExpiration: 60
  refreshTokenExpiration: 2592000

r2dbc:
  url: "???"

aws:
  s3:
    region: "???"
    accessKeyId: "???"
    secretAccessKey: "???"
    endpoint: "???"
    bucket: "???"

logback:
  production: true