ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.maeasoftworks.normativecontrol.api.ApplicationKt.initialize
  development: true

jwt:
  issuer: "normative-control.ru"
  audience: "normative-control.ru"
  realm: "normative-control.ru"
  secret: "XRQaA5ABbDbTosUYTW5WRukcQ8+U6mzvNh8mYXFkZ7c="
  jwtTokenExpiration: 922752000
  refreshTokenExpiration: 922752000

r2dbc:
  url: "r2dbc:postgresql://postgres:maeasoftworks@localhost:5432/normative-control"

aws:
  s3:
    region: "US-EAST-1"
    accessKeyId: "Shw0FrU99u0wxPwnD83y"
    secretAccessKey: "MrvC4T96ngCoPVlsvL5dgP8HBtRezqLqISDWFfl7"
    endpoint: "http://localhost:9000"
    bucket: "normative-control"

logback:
  dev: true