ktor:
  application:
    modules:
      - ru.maeasoftworks.normativecontrol.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  issuer: "normative-control.ru"
  audience: "normative-control.ru"
  realm: "normative-control.ru"
  secret: "XRQaA5ABbDbTosUYTW5WRukcQ8+U6mzvNh8mYXFkZ7c="
r2dbc:
  username: "postgres"
  url: "r2dbc:postgresql://postgres:maeasoftworks@localhost:5432/normative-control"
  password: "maeasoftworks"
  pool:
    enabled: true
aws:
  s3:
    region: "US-EAST-1"
    accessKeyId: "TLLOX30bWCuHCYkUwzdc"
    secretAccessKey: "ZaVrjzV4Kw0OGAYObJjH2T6IPcscuUeGYPLahU5s"
    endpoint: "http://localhost:9000"
    bucket: "normative-control"