package com.prmncr.normativecontrol.dtos;

public enum ErrorType {
    INCORRECT_PAGE_SIZE,
    INCORRECT_PAGE_MARGINS,
    INCORRECT_SECTORS,
    INCORRECT_TEXT_FONT,
    INCORRECT_HEADER_FONT_SIZE,
    INCORRECT_TEXT_COLOR,
    INCORRECT_HEADER_ALIGNMENT,
    HEADER_IS_NOT_UPPERCASE,
    INCORRECT_FONT_SIZE,
    INCORRECT_REGULAR_TEXT_ALIGNMENT,
    ITALIC_TEXT,
    REGULAR_TEXT_WAS_BOLD,
    REGULAR_TEXT_WAS_UNDERLINED,
    STRIKETHROUGH,
    HIGHLIGHT,
    INCORRECT_TEXT_DIRECTION,
    BORDER,
    BACKGROUND_FILLED
}
