package com.prmncr.normativecontrol.dtos;

public enum ErrorType {
    INCORRECT_PAGE_SIZE,
    INCORRECT_PAGE_MARGINS,
    INCORRECT_SECTORS,
    BUILT_IN_HEADER_STYLE_IS_NOT_USED,
    INCORRECT_TEXT_FONT,
    INCORRECT_HEADER_FONT_SIZE,
    INCORRECT_TEXT_COLOR,
    INCORRECT_HEADER_ALIGNMENT,
    HEADER_IS_NOT_UPPERCASE,
    INCORRECT_FONT_SIZE
}
